# Generated by Django 2.0.1 on 2018-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiHiring', '0002_registerlogin_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
